# The following settings are absolutely required for the CR adaptor to work
script.disable_dynamic: sandbox
script.groovy.sandbox.class_whitelist: java.util.LinkedHashMap
script.groovy.sandbox.receiver_whitelist:  java.util.Iterator, java.lang.Object, java.util.Map, java.util.Map$Entry
script.groovy.sandbox.enabled: true

# the following settings secure your cluster, name should be uniq, use: `pwgen -Bsv1 64`
cluster.name: B6wDXSnqM6sfMGmlh8bj8XhpgZgFcfQm5JW5vD29QWthsfwKP4dmm4mMBQTpb2gD
network.host: 0.0.0.0

# the following settings are well-suited for smaller ElasticSearch instances (e.g. as long as you can stay on one host)
index.number_of_shards: 1
index.number_of_replicas: 0
