###############################################
## PHP FPM
phpfpm:
  image: zeroboh/php
  volumes_from:
    - storage
  links:
    - redis
    - elasticsearch
    - mariadb

###############################################
## WebApp
webapp:
  image: zeroboh/nginx
  volumes_from:
    - storage
  ports:
   - 81:80
  links:
    - phpfpm

###############################################
## MariaDB
mariadb:
  image: zeroboh/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_DATABASE: 'database'
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'password'

###############################################
## Redis
redis:
  image: zeroboh/redis

###############################################
## Elasticsearch
elasticsearch:
  image: zeroboh/elasticsearch

###############################################
## Data Storage
storage:
  image: zeroboh/storage
  volumes:
    - ./data:/data
  command: 'true'
